### PR TITLE
instructions for beginners

### PR DESCRIPTION
**Pull request by juliamrch**
Instructions for beginners who host a small website and aren't familiar with command lines.

### CODE REVIEW

**Comment by juliamrch** [comment]
Hi, 

Thanks for the review, and sorry for the PRs, apparently I couldn’t manage to delete the 2 previous one 💀 I will definitely check ressources about contributing on GitHub.

> Could you say where this idea stemmed from? The Android client has had some issues in that it [always showed as connected](https://community.signalusers.org/t/running-and-testing-signal-proxy/47465/2) regardless of whether it was actually true.

It stemmed precisely because I had the idea to try this method on one of my servers (which is max pain to connect to via shell but has the advantage to let me change its IPs as I wish) , and checked my proxy url right after. The proxy seemed to work, the Signal page to download the app appeared asking if I wanted to download the app. 

Just to be clear, now that the files are hosted, if I connect to the server via ssh and run the command, the proxy would start, right ?

**Comment by local-optimum** [comment]
Hey folks, I'm trying to install this on a Raspberry Pi but you seem to have an amd64 specific element of your code (potentially from certbot) that is preventing it from running correctly on arm.

The error appears after running `sudo ./init-certificate.sh`

````
### Requesting Let's Encrypt certificate for DOMAINNAMEREPLACED ...
Creating network "signal-tls-proxy_default" with the default driver
Pulling certbot (certbot/certbot:)...
latest: Pulling from certbot/certbot
339de151aab4: Pull complete
a860e27ad689: Pull complete
910a9a405b4b: Pull complete
bde2ad12a253: Pull complete
c6c8e9f0153d: Pull complete
ee185b36c37e: Pull complete
baedaa7e0794: Pull complete
8a9b412afa74: Pull complete
e69b0d58d2b4: Pull complete
6e266a1f6d9d: Pull complete
14bb8fb58f70: Pull complete
baaa7e601a29: Pull complete
b55a5f4fe626: Pull complete
Digest: sha256:3103d00d7733379cb540aa03b714b999fafc21fd27cf88571e386f656696c4ec
Status: Downloaded newer image for certbot/certbot:latest
Creating signal-tls-proxy_certbot_run ... done
exec /bin/sh: exec format error
ERROR: 1
````

Raspberry Pi seems perfect for this use-case so if it's possible to support arm that would be amazing.

**Comment by stinky-fox** [comment]
arm64 would be amazing!

and would be nice to have some other option how to verify whether it's working or not. Like logs or whatever

**Comment by zhksh** [comment]
it depends on the arch of your Raspberry @local-optimum your error looks like an error msg from go. i have my proxy running on an older Raspberry 3 with an armv7 arch. Adjusting the ubuntu-docker as well as the certbot images was necessary: https://github.com/zhksh/Signal-TLS-Proxy/tree/arm7-images

**Comment by zhksh** [comment]
@stinky-fox you can check with docker-compose ps and docker-compose logs -f (after switching to the root of your repo directory)

**Comment by stinky-fox** [comment]
> @stinky-fox you can check with docker-compose ps and docker-compose logs -f (after switching to the root of your repo directory)

I know that but it helps if container is providing anything. So a simple "all good, I'm up" could help a lot of new users to check whether their proxy is up and running or no.

**Comment by rbxxswap** [comment]
Hello, can somone help to install on a Plesk running Server?

**Pull request closed without merging**
