### PR TITLE
Add HAProxy as second proxy option

### PR DESCRIPTION
**Pull request by git001**
Because there are no issues possible I add my questions here.

I try to add as second solution the HAProxy. HAProxy offers the possibility to check the backend servers and I have add the DNS resolving to get the DNS Changes for the backends.

The problem what  I got is that  TextSecure / Open Whisper Systems uses there own CA.
Is there a Download URL where the CA could be downloaded to verify the CA?

I was necessary to disable the ssl verify which I would like to enable it.
 # http://cbonte.github.io/haproxy-dconv/2.3/configuration.html#ssl-server-verify
 ssl-server-verify none

Another topic is that it looks to me the backend servers blocks the checks and therefore I get "General socket error (Network is unreachable)" on layer 4. A curl to the backend server works from the same server.

### CODE REVIEW

**Review by ralphstone1 — CHANGES_REQUESTED** [review]
Information please

**Comment by git001** [comment]
@ralphstone1 Please can you tell me what Information do you want?

**Comment by SvenKiljan** [comment]
@git001

You can read this article on how to configure HAProxy as a Signal TLS Proxy:

https://kiljan.org/2021/04/11/integrating-a-signal-tls-proxy-in-an-existing-site-using-haproxy/

No changes are needed on the side of the Signal servers. `ssl-server-verify none` is not necessary.

**Comment by git001** [comment]
With the blog post above can the issue be closed from my point of view

**Pull request closed without merging**
